name: Scheduled Web Requests # Workflow 的名称，可以自定义

on:
  schedule:
    - cron: '*/30 * * * *' # 每半小时运行一次
    - cron: '0 0 * * *'    # 每天 UTC 时间 00:00 运行一次 (即每天的午夜)

jobs:
  call-urls:
    runs-on: ubuntu-latest # 运行在 Ubuntu 最新版本的虚拟机上

    steps:
      - name: 每半小时访问 - ziyuanku
        run: curl http://b.you.anneng.ggff.net/api.php/timming/index.html?enforce=1&name=ziyuanku

      - name: 每天访问 - haibao (you.anneng.ggff.net)
        run: curl http://b.you.anneng.ggff.net/bbj/haibao.php?cmsname=maccms10&bbjtype=hot&codetype=php&filtercondi=doubanid&orderby=ASC&num=10&level=9

      - name: 每半小时访问 - hongniuzy
        run: curl https://ane.anneng.ggff.net/api.php/timming/index.html?enforce=1&name=hongniuzy

      - name: 每半小时访问 - aa
        run: curl https://dy.wangzhetq.asia/api.php/timming/index.html?enforce=1&name=aa

      - name: 每天访问 - haibao (ane.anneng.ggff.net)
        run: curl https://ane.anneng.ggff.net/bbj/haibao.php?cmsname=maccms10&bbjtype=hot&codetype=php&filtercondi=doubanid&orderby=ASC&num=10&level=9
