name: Scheduled Tasks

on:
  # 每半小时触发一次
  schedule:
    - cron: "*/30 * * * *"
  
  # 每天 UTC 时间 0:00（北京时间 8:00）触发一次
  schedule:
    - cron: "0 0 * * *"

jobs:
  half-hourly:
    if: contains(github.event.schedule, '*/30')
    runs-on: ubuntu-latest
    steps:
      - name: Request URL 1
        run: curl -sS "https://ane.anneng.ggff.net/api.php/timming/index.html?enforce=1&name=hongniuzy"
      - name: Request URL 2
        run: curl -sS "https://dy.wangzhetq.asia/api.php/timming/index.html?enforce=1&name=aa"

  daily:
    if: contains(github.event.schedule, '0 0')
    runs-on: ubuntu-latest
    steps:
      - name: Make daily request
        run: curl -sS "https://ane.anneng.ggff.net/bbj/haibao.php?cmsname=maccms10&bbjtype=hot&codetype=php&filtercondi=doubanid&orderby=ASC&num=10&level=9"
