name: Scheduled Requests

on:
 schedule:
   # 每半小时执行一次
   - cron: '*/30 * * * *'
   # 每天执行一次
   - cron: '0 0 * * *'

jobs:
 request:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Access webpage every half hour
       if: github.event.schedule != null && github.event.schedule == '*/30 * * * *'
       run: |
         curl "http://b.you.anneng.ggff.net/api.php/timming/index.html?enforce=1&name=ziyuanku"
         curl "https://ane.anneng.ggff.net/api.php/timming/index.html?enforce=1&name=hongniuzy"
         curl "https://dy.wangzhetq.asia/api.php/timming/index.html?enforce=1&name=aa"

     - name: Access webpage once a day
       if: github.event.schedule != null && github.event.schedule == '0 0 * * *'
       run: |
         curl "http://b.you.anneng.ggff.net/bbj/haibao.php?cmsname=maccms10&bbjtype=hot&codetype=php&filtercondi=doubanid&orderby=ASC&num=10&level=9"
         curl "https://ane.anneng.ggff.net/bbj/haibao.php?cmsname=maccms10&bbjtype=hot&codetype=php&filtercondi=doubanid&orderby=ASC&num=10&level=9"
