name: Scheduled Requests

on:
  schedule:
    # 每半小时执行一次
    - cron: '*/30 * * * *'
    # 每天执行一次
    - cron: '0 0 * * *'
  workflow_dispatch:  # 添加手动触发选项

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Access webpage every half hour
        run: |
          # 定义半小时检查的 URL 数组
          declare -A HALF_HOURLY_URLS
          HALF_HOURLY_URLS=(
            ["hongniuzy"]="https://ane.anneng.ggff.net/api.php/timming/index.html?enforce=1&name=hongniuzy"
            ["bing522"]="https://bing522.serv00.net/api.php/timming/index.html?enforce=1&name=aa"
          )

          # 遍历并检查每个 URL
          for name in "${!HALF_HOURLY_URLS[@]}"; do
            url="${HALF_HOURLY_URLS[$name]}"
            STATUS_CODE=$(curl -s -w "%{http_code}" "$url" -o /dev/null)
            if [ "$STATUS_CODE" -eq "200" ]; then
              echo "✅ 成功访问 $name 接口 ($url)，状态码: $STATUS_CODE"
            else
              echo "❌ 访问 $name 接口失败 ($url)，状态码: $STATUS_CODE"
            fi
          done

      - name: Access webpage once a day
        run: |
          # 定义每天检查的 URL 数组
          declare -A DAILY_URLS
          DAILY_URLS=(
            
            ["haibao2"]="https://ane.anneng.ggff.net/bbj/haibao.php?cmsname=maccms10&bbjtype=hot&codetype=php&filtercondi=doubanid&orderby=ASC&num=10&level=9"
          )

          # 遍历并检查每个 URL
          for name in "${!DAILY_URLS[@]}"; do
            url="${DAILY_URLS[$name]}"
            STATUS_CODE=$(curl -s -w "%{http_code}" "$url" -o /dev/null)
            if [ "$STATUS_CODE" -eq "200" ]; then
              echo "✅ 成功访问 $name 接口 ($url)，状态码: $STATUS_CODE"
            else
              echo "❌ 访问 $name 接口失败 ($url)，状态码: $STATUS_CODE"
            fi
          done
